import type { Artifact } from './types';

export const artifacts = [
  {
    id: 'agro-commodity-trading-infrastructure',
    slug: 'agro-commodity-trading-infrastructure',
    title: 'Agro-commodity trading infrastructure',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Current focus area around digital infrastructure for physical agro-commodity markets, trading workflows, monitoring, and market-risk tools.',
    description:
      'A working umbrella for market infrastructure projects connected to grain, oilseeds, brokerage, dashboards, monitors, and digital operating layers for physical commodity trading.',
    tags: ['agro-commodities', 'market-infrastructure', 'trading', 'risk-tools'],
    links: [],
    featured: true,
    sortRank: 10,
    needsReview: true,
  },
  {
    id: 'cropto',
    slug: 'cropto',
    title: 'Cropto',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Cropto-related commodity trading infrastructure and service layer for market tools, monitors, and trading workflows.',
    tags: ['cropto', 'commodities', 'trading-infrastructure'],
    links: [],
    featured: true,
    sortRank: 20,
    needsReview: true,
  },
  {
    id: 'liqua',
    slug: 'liqua',
    title: 'Liqua',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Structured market liquidity project for physical commodity trading.',
    tags: ['commodities', 'liquidity', 'market-infrastructure'],
    links: [],
    featured: true,
    sortRank: 30,
    needsReview: true,
  },
  {
    id: 'trade-solution-eu',
    slug: 'trade-solution-eu',
    title: 'Trade Solution EU',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Trading-related landing/service project connected to the agro-commodity infrastructure work.',
    tags: ['commodities', 'trading', 'landing'],
    links: [],
    featured: false,
    sortRank: 40,
    needsReview: true,
  },
  {
    id: 'abvx-shortener',
    slug: 'abvx-shortener',
    title: 'ABVX Shortener',
    type: 'web-service',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'Small self-hosted URL shortener and web-service utility.',
    tags: ['web-service', 'utility', 'cloudflare'],
    links: [],
    featured: false,
    sortRank: 110,
    needsReview: true,
  },
  {
    id: 'agents-md-generator',
    slug: 'agents-md-generator',
    title: 'AGENTS.md Generator',
    type: 'ai-workflow',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'AI-development workflow tool for generating strict, actionable AGENTS.md files for coding agents.',
    tags: ['ai-dev', 'agents', 'documentation', 'workflow'],
    links: [
      {
        label: 'Website',
        url: 'https://agentsmd.abvx.xyz/',
      },
    ],
    featured: true,
    sortRank: 100,
    needsReview: true,
  },
  {
    id: 'ascii-theme',
    slug: 'ascii-theme',
    title: 'AsciiTheme',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'Framework-agnostic micro-package for adding an experimental ASCII visual theme mode to websites.',
    tags: ['ui', 'theme', 'ascii', 'web-tool'],
    links: [
      {
        label: 'GitHub',
        url: 'https://github.com/markoblogo/AsciiTheme',
      },
    ],
    featured: true,
    sortRank: 120,
    needsReview: false,
  },
  {
    id: 'toki-pona-language-projects',
    slug: 'toki-pona-language-projects',
    title: 'Toki Pona language projects',
    type: 'language-experiment',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'released',
    summary:
      'Constructed-language work around Toki Pona: translations, services, protocols, and publishing companions.',
    tags: ['toki-pona', 'language-ai', 'constructed-language', 'translation'],
    links: [],
    featured: true,
    sortRank: 200,
    needsReview: true,
  },
] satisfies Artifact[];
