import type { Artifact, ContentLinkType, MediaRole } from './types';

// Legacy archive only. Runtime content is loaded from /content/work.
// Use `npm run content:parity` before deleting or changing this archive.

function image(slug: string, alt: string, folder = 'projects', mediaRole: MediaRole = 'project-screenshot') {
  return { src: `/media/${folder}/${slug}.png`, alt, mediaRole };
}

function link(type: ContentLinkType, label: string, url: string) {
  return { type, label, url };
}

export const artifacts = [
  {
    id: 'cropto',
    slug: 'cropto',
    title: 'Cropto — Human-Centred Crypto Clarity',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Core Cropto platform entry for commodity trading infrastructure, market tools, monitors, and risk workflows.',
    description:
      'Cropto is the public platform layer for the agro-commodity trading infrastructure work: a home for market-risk tooling, monitors, dashboards, and service interfaces around physical commodity markets.',
    tags: ['cropto', 'commodities', 'market-infrastructure', 'trading-platform'],
    links: [
      link('website', 'Site', 'https://cropto.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/cropto-v0'),
      link('youtube', 'YouTube', 'https://youtu.be/zumLJKZQFxc'),
    ],
    thumbnail: image('cropto', 'Cropto platform screenshot'),
    heroImage: image('cropto', 'Cropto platform screenshot'),
    group: 'Trading platforms',
    featured: true,
    sortRank: 10,
    needsReview: false,
  },
  {
    id: 'cropto-monitor',
    slug: 'cropto-monitor',
    title: 'Cropto Monitor: Commodity Signals Terminal',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Commodity signals terminal for monitoring market data and trading conditions.',
    description:
      'A Cropto dashboard/monitor project focused on market signals and structured situational awareness for physical commodity trading.',
    tags: ['cropto', 'monitor', 'commodity-signals', 'dashboard'],
    links: [
      link('website', 'Site', 'https://cropto.abvx.xyz/monitor'),
      link('github', 'GitHub', 'https://github.com/markoblogo/cropto-v0'),
    ],
    thumbnail: image('cropto-monitor', 'Cropto Monitor screenshot'),
    heroImage: image('cropto-monitor', 'Cropto Monitor screenshot'),
    group: 'Trading dashboards',
    featured: true,
    sortRank: 20,
    needsReview: false,
  },
  {
    id: 'cropto-market-risk-deck',
    slug: 'cropto-market-risk-deck',
    title: 'Cropto market risk tools deck',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Deck and landing page for local market risk tools, spot indices, hedging, options, and cross-market strategies.',
    description:
      'A Cropto presentation/landing artifact explaining how local market risk tools can become modern digital infrastructure for commodity markets.',
    tags: ['cropto', 'market-risk', 'deck', 'landing'],
    links: [
      link('website', 'Site', 'https://cropto.abvx.xyz/deck/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/cropto-v0'),
      link('youtube', 'YouTube', 'https://youtu.be/zumLJKZQFxc'),
    ],
    thumbnail: image('cropto-market-risk-deck', 'Cropto market risk deck screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('cropto-market-risk-deck', 'Cropto market risk deck screenshot', 'projects', 'landing-screenshot'),
    group: 'Landing pages',
    featured: false,
    sortRank: 30,
    needsReview: false,
  },
  {
    id: 'liqua',
    slug: 'liqua',
    title: 'Liqua',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'building',
    summary:
      'Liquidity layer for physical commodity markets and structured market liquidity.',
    description:
      'Liqua is a Cropto-adjacent landing/service project for structured market liquidity in physical commodity trading.',
    tags: ['commodities', 'liquidity', 'market-infrastructure', 'trading-service'],
    links: [
      link('website', 'Site', 'https://liqua.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/liqua'),
      link('youtube', 'YouTube', 'https://youtu.be/f8te3FBX32I'),
    ],
    thumbnail: image('liqua', 'Liqua landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('liqua', 'Liqua landing screenshot', 'projects', 'landing-screenshot'),
    group: 'Trading services',
    featured: true,
    sortRank: 40,
    needsReview: false,
  },
  {
    id: 'trade-solution-eu',
    slug: 'trade-solution-eu',
    title: 'Trade Solution EU',
    type: 'market-infrastructure',
    primarySection: 'focus',
    appearsIn: ['focus', 'systems'],
    status: 'live',
    summary:
      'Trading landing/service layer around live market signals and structured decisions.',
    description:
      'Trade Solution EU is a public trading-services landing project connected to the agro-commodity infrastructure work.',
    tags: ['commodities', 'trading', 'market-signals', 'landing'],
    links: [
      link('website', 'Site', 'https://trade-solution.eu/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/TS'),
      link('youtube', 'YouTube', 'https://youtu.be/YOFrlLiPY6A'),
    ],
    thumbnail: image('trade-solution-eu', 'Trade Solution EU screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('trade-solution-eu', 'Trade Solution EU screenshot', 'projects', 'landing-screenshot'),
    group: 'Trading services',
    featured: false,
    sortRank: 50,
    needsReview: false,
  },
  {
    id: 'agents-md-generator',
    slug: 'agents-md-generator',
    title: 'AGENTS.md Generator',
    type: 'ai-workflow',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'Safe-by-default CLI that generates and updates AGENTS.md / RUNBOOK.md for AI coding agents.',
    description:
      'A diff-first, marker-based workflow tool for generating strict, actionable repository instructions for coding agents.',
    tags: ['ai-dev', 'agents', 'documentation', 'workflow'],
    links: [
      link('website', 'Site', 'https://agentsmd.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/AGENTS.md_generator'),
    ],
    thumbnail: image('agents-md-generator', 'AGENTS.md Generator landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('agents-md-generator', 'AGENTS.md Generator landing screenshot', 'projects', 'landing-screenshot'),
    group: 'AI/dev stack',
    featured: true,
    sortRank: 100,
    needsReview: false,
  },
  {
    id: 'ascii-theme',
    slug: 'ascii-theme',
    title: 'AsciiTheme',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'Open-source ASCII UI theme for modern websites, with CSS/JS and light/dark awareness.',
    description:
      'A framework-agnostic micro-package for adding an experimental ASCII visual theme mode to websites.',
    tags: ['ui', 'theme', 'ascii', 'web-tool'],
    links: [
      link('github', 'GitHub', 'https://github.com/markoblogo/AsciiTheme'),
      link('youtube', 'YouTube', 'https://youtu.be/VVQX7DtGHX0'),
    ],
    thumbnail: image('ascii-theme', 'AsciiTheme screenshot'),
    heroImage: image('ascii-theme', 'AsciiTheme screenshot'),
    group: 'AI/dev stack',
    featured: true,
    sortRank: 110,
    needsReview: false,
  },
  {
    id: 'abvx-shortener',
    slug: 'abvx-shortener',
    title: 'ABVX Shortener',
    type: 'web-service',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'live',
    summary:
      'Private, zero-bloat link shortener with a one-click browser workflow.',
    tags: ['web-service', 'utility', 'shortener'],
    links: [
      link('github', 'GitHub', 'https://github.com/markoblogo/-abvx-shortener'),
      link('youtube', 'YouTube', 'https://youtu.be/oEPow5tKjXQ'),
    ],
    thumbnail: image('abvx-shortener', 'ABVX Shortener screenshot'),
    heroImage: image('abvx-shortener', 'ABVX Shortener screenshot'),
    group: 'Web services',
    featured: false,
    sortRank: 120,
    needsReview: false,
  },
  {
    id: 'toki-pona-ai-translator',
    slug: 'toki-pona-ai-translator',
    title: 'Toki Pona AI translator',
    type: 'language-experiment',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'live',
    summary:
      'Playful translator from any language into Toki Pona, sitelen pona and sitelen emoji.',
    tags: ['toki-pona', 'language-ai', 'translator', 'ai-service'],
    links: [
      link('website', 'Site', 'https://toki.abvx.xyz'),
      link('github', 'GitHub', 'https://github.com/markoblogo/toki-pona-translator'),
      link('youtube', 'YouTube', 'https://youtu.be/lCAFiDnP2NQ?si=HOEWm4Cr1VVRitPt'),
    ],
    thumbnail: image('toki-pona-ai-translator', 'Toki Pona AI translator screenshot'),
    heroImage: image('toki-pona-ai-translator', 'Toki Pona AI translator screenshot'),
    group: 'AI services',
    featured: true,
    sortRank: 200,
    needsReview: false,
  },
  {
    id: 'chinese-wisdom-toki-pona-landing',
    slug: 'chinese-wisdom-toki-pona-landing',
    title: 'Chinese Wisdom in toki pona landing',
    type: 'book-companion',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'live',
    summary:
      'Landing page for Chinese Wisdom in Toki Pona books and companion material.',
    tags: ['toki-pona', 'book-companion', 'landing', 'dao'],
    links: [
      link('website', 'Site', 'https://dao-toki.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/dao-toki'),
    ],
    thumbnail: image('chinese-wisdom-toki-pona-landing', 'Chinese Wisdom in toki pona landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('chinese-wisdom-toki-pona-landing', 'Chinese Wisdom in toki pona landing screenshot', 'projects', 'landing-screenshot'),
    group: 'Landing pages',
    featured: false,
    sortRank: 210,
    needsReview: false,
  },
  {
    id: 'stoic-wisdom-toki-pona-landing',
    slug: 'stoic-wisdom-toki-pona-landing',
    title: 'Stoic Wisdom in Toki Pona landing',
    type: 'book-companion',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'live',
    summary:
      'Landing page for classic Stoic texts reimagined in Toki Pona and sitelen pona.',
    tags: ['toki-pona', 'stoicism', 'book-companion', 'landing'],
    links: [
      link('website', 'Site', 'https://stoic.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/stoic-wisdom-series'),
    ],
    thumbnail: image('stoic-wisdom-toki-pona-landing', 'Stoic Wisdom in Toki Pona landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('stoic-wisdom-toki-pona-landing', 'Stoic Wisdom in Toki Pona landing screenshot', 'projects', 'landing-screenshot'),
    group: 'Landing pages',
    featured: false,
    sortRank: 220,
    needsReview: false,
  },
  {
    id: 'toki-pona-free-kits-landing',
    slug: 'toki-pona-free-kits-landing',
    title: 'Toki Pona free kits landing',
    type: 'book-companion',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'live',
    summary:
      'Landing page for free Toki Pona kits and translations with direct downloads.',
    tags: ['toki-pona', 'free-books', 'book-companion', 'landing'],
    links: [
      link('website', 'Site', 'https://toki-free.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/toki-free-kit'),
    ],
    thumbnail: image('toki-pona-free-kits-landing', 'Toki Pona free kits landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('toki-pona-free-kits-landing', 'Toki Pona free kits landing screenshot', 'projects', 'landing-screenshot'),
    group: 'Landing pages',
    featured: false,
    sortRank: 230,
    needsReview: false,
  },
  {
    id: 'ukrainian-modernism-landing',
    slug: 'ukrainian-modernism-landing',
    title: 'Ukrainian Modernism landing',
    type: 'book-companion',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'live',
    summary:
      'Bilingual editorial landing page showcasing Ukrainian modernist literature for a French-speaking audience.',
    tags: ['ukrainian-modernism', 'translation', 'book-companion', 'landing'],
    links: [
      link('website', 'Site', 'https://ukrmodernism.abvx.xyz/'),
      link('github', 'GitHub', 'https://github.com/markoblogo/ukrainian-modernism'),
      link('youtube', 'YouTube', 'https://youtu.be/krXa1OzLVIs?si=RpMnZ340bGVTBz4I'),
    ],
    thumbnail: image('ukrainian-modernism-landing', 'Ukrainian Modernism landing screenshot', 'projects', 'landing-screenshot'),
    heroImage: image('ukrainian-modernism-landing', 'Ukrainian Modernism landing screenshot', 'projects', 'landing-screenshot'),
    group: 'Landing pages',
    featured: false,
    sortRank: 240,
    needsReview: false,
  },
  {
    id: 'sitelen-emoji-truth',
    slug: 'sitelen-emoji-truth',
    title: 'sitelen-emoji-truth',
    type: 'protocol',
    primarySection: 'systems',
    appearsIn: ['systems', 'books'],
    status: 'released',
    summary:
      'Pinned source-of-truth mapping for toki pona to sitelen emoji, with reproducible, book-ready visuals.',
    tags: ['toki-pona', 'sitelen-emoji', 'protocol', 'publishing'],
    links: [
      link('substack', 'Substack', 'https://abvx.substack.com/p/freezing-a-moving-target-a-source'),
      link('github', 'GitHub', 'https://github.com/markoblogo/sitelen-emoji-truth'),
    ],
    thumbnail: image('sitelen-emoji-truth', 'sitelen-emoji-truth cover', 'projects', 'mockup'),
    heroImage: image('sitelen-emoji-truth', 'sitelen-emoji-truth cover', 'projects', 'mockup'),
    group: 'Language experiments',
    featured: false,
    sortRank: 250,
    needsReview: false,
  },
  {
    id: 'ytmamp',
    slug: 'ytmamp',
    title: 'YTMamp',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'released',
    summary:
      'Lightweight, retro-inspired mini-player for YouTube Music on macOS.',
    tags: ['macos', 'music', 'tool', 'youtube-music'],
    links: [
      link('github', 'GitHub', 'https://github.com/markoblogo/YTMamp'),
      link('youtube', 'YouTube', 'https://youtu.be/fHRDm8e2n-U?si=mnMXHU2qv5MIN8G6'),
    ],
    thumbnail: image('ytmamp', 'YTMamp screenshot'),
    heroImage: image('ytmamp', 'YTMamp screenshot'),
    group: 'Tools',
    featured: false,
    sortRank: 400,
    needsReview: false,
  },
  {
    id: 'abvx-lab',
    slug: 'abvx-lab',
    title: 'ABVX Lab',
    type: 'web-service',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'building',
    summary:
      'Public lab surface for experiments, prototypes, and AI-native development utilities.',
    tags: ['lab', 'experiments', 'ai-dev'],
    links: [link('website', 'Site', 'https://lab.abvx.xyz/')],
    group: 'AI/dev stack',
    featured: false,
    sortRank: 500,
    needsReview: true,
    mediaNeedsReview: true,
  },
  {
    id: 'git-tweet',
    slug: 'git-tweet',
    title: 'git-tweet',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'archive',
    summary:
      'Small development utility from the legacy public projects list; public links need review before promotion.',
    tags: ['tool', 'developer-utility'],
    links: [],
    group: 'Tools',
    featured: false,
    sortRank: 510,
    needsReview: true,
    mediaNeedsReview: true,
  },
  {
    id: 'id',
    slug: 'id',
    title: 'ID',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'building',
    summary:
      'Open-source development project from the AI/dev stack; public description and links need final review.',
    tags: ['ai-dev', 'tool'],
    links: [link('github', 'GitHub', 'https://github.com/markoblogo/ID')],
    group: 'AI/dev stack',
    featured: false,
    sortRank: 520,
    needsReview: true,
    mediaNeedsReview: true,
  },
  {
    id: 'set',
    slug: 'set',
    title: 'SET',
    type: 'tool',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'building',
    summary:
      'Open-source development project from the AI/dev stack; public description and links need final review.',
    tags: ['ai-dev', 'tool'],
    links: [link('github', 'GitHub', 'https://github.com/markoblogo/SET')],
    group: 'AI/dev stack',
    featured: false,
    sortRank: 530,
    needsReview: true,
    mediaNeedsReview: true,
  },
  {
    id: 'mn7r',
    slug: 'mn7r',
    title: 'MN7R',
    type: 'research',
    primarySection: 'systems',
    appearsIn: ['systems'],
    status: 'archive',
    summary:
      'Legacy public project record retained for parity; keep archived until content and links are reviewed.',
    tags: ['archive', 'research'],
    links: [],
    group: 'Tools',
    featured: false,
    sortRank: 540,
    needsReview: true,
    mediaNeedsReview: true,
  },
] satisfies Artifact[];
