import type { Book, ContentLinkType } from './types';

function cover(slug: string, alt: string) {
  const extension = new Set(['future-proof', 'christmas-carol-toki-pona']).has(slug)
    ? 'jpg'
    : 'png';
  return { src: `/media/books/${slug}.${extension}`, alt };
}

function link(type: ContentLinkType, label: string, url: string) {
  return { type, label, url };
}

const ukrSeries = 'Ukrainian Modernism';
const tokiClassics = 'Toki Pona Classics';
const stoicSeries = 'Stoic Wisdom in Toki Pona';
const chineseSeries = 'Chinese Wisdom in Toki Pona';

export const books = [
  {
    id: 'ukrainian-modernism-series',
    slug: 'ukrainian-modernism-series',
    title: 'Ukrainian Modernism translations',
    type: 'series',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Series of early twentieth-century Ukrainian modernist literature translated into French.',
    description:
      'A publishing series presenting Ukrainian modernist authors to a French-speaking audience through books, free editions, teasers, and a bilingual companion site.',
    tags: ['ukrainian-modernism', 'translations', 'french', 'literature'],
    links: [link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr')],
    series: ukrSeries,
    category: 'Translations',
    formats: ['series-site'],
    featured: true,
    sortRank: 10,
    needsReview: false,
  },
  {
    id: 'toki-pona-classics-series',
    slug: 'toki-pona-classics-series',
    title: 'Toki Pona Classics',
    type: 'series',
    primarySection: 'books',
    appearsIn: ['books', 'systems'],
    status: 'released',
    summary:
      'Toki Pona book series, reader kits, free editions, and companion websites around classics, philosophy, and language experiments.',
    tags: ['toki-pona', 'translations', 'constructed-language', 'series'],
    links: [
      link('series-site', 'Stoic Series', 'https://stoic.abvx.xyz/en'),
      link('series-site', 'Chinese Wisdom', 'https://dao-toki.abvx.xyz/'),
      link('series-site', 'Free Kits', 'https://toki-free.abvx.xyz/en'),
    ],
    series: tokiClassics,
    category: 'Series',
    formats: ['series-site', 'free-editions'],
    featured: true,
    sortRank: 20,
    needsReview: false,
  },
  {
    id: 'dark-gestalt',
    slug: 'dark-gestalt',
    title: 'Dark Gestalt: How Brands Hijack Emotions, Distort Perception, and Manufacture Desire',
    type: 'book',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'A business and psychology book about emotional manipulation, perception, desire, and brand systems.',
    tags: ['marketing', 'psychology', 'business', 'brands'],
    links: [
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0FT5V3QCL'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0FTLQXWY1'),
      link('youtube', 'YouTube', 'https://youtu.be/QjZgzs845yI'),
    ],
    coverImage: cover('dark-gestalt', 'Dark Gestalt book cover'),
    series: 'Business & Productivity',
    category: 'Business & Productivity',
    formats: ['kindle', 'paperback'],
    featured: true,
    sortRank: 100,
    needsReview: false,
  },
  {
    id: 'future-proof-productivity',
    slug: 'future-proof-productivity',
    title: 'Future-Proof Your Productivity: Navigating the AI Decade to Accelerate Your Output, Innovate Your Role, and Thrive',
    type: 'book',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'A productivity and AI book about adapting work, output, and roles during the AI decade.',
    tags: ['ai', 'productivity', 'business', 'future-of-work'],
    links: [
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0FQ5SWMTJ'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0FR1WH15S'),
      link('youtube', 'YouTube', 'https://youtu.be/IJBn0x2UeF8'),
    ],
    coverImage: cover('future-proof', 'Future-Proof Your Productivity book cover'),
    series: 'Business & Productivity',
    category: 'Business & Productivity',
    formats: ['kindle', 'paperback'],
    featured: true,
    sortRank: 110,
    needsReview: false,
  },
  {
    id: 'llmo-seo-revolution',
    slug: 'llmo-seo-revolution',
    title: 'LLMO: The Next SEO Revolution',
    type: 'book',
    primarySection: 'books',
    appearsIn: ['books', 'systems'],
    status: 'released',
    summary:
      'Book project on staying visible to AI systems in the age of zero-click discovery.',
    tags: ['llmo', 'ai-search', 'visibility', 'books'],
    links: [
      link('book-site', 'Site', 'https://llmo.abvx.xyz/'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0FYRSSZKL'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0G1YBYKDR'),
      link('youtube', 'YouTube', 'https://youtu.be/0l_fawMcPmw'),
    ],
    coverImage: cover('llmo-seo-revolution', 'LLMO: The Next SEO Revolution book cover'),
    series: 'Business & Productivity',
    category: 'Language & AI',
    formats: ['kindle', 'paperback', 'book-site'],
    featured: true,
    sortRank: 120,
    needsReview: false,
  },
  {
    id: 'toki-pona-machine-mind',
    slug: 'toki-pona-machine-mind',
    title: 'Toki Pona and the Machine Mind',
    type: 'book',
    primarySection: 'books',
    appearsIn: ['books', 'systems'],
    status: 'released',
    summary:
      'Book on using the world’s simplest language to think about cleaner prompts, smaller models, and better systems.',
    tags: ['toki-pona', 'ai', 'language-ai', 'prompting'],
    links: [
      link('book-site', 'Site', 'https://toki.abvx.xyz/learn'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0G44JSMR2'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0G5MQKZTX'),
      link('youtube', 'YouTube', 'https://youtu.be/0juEOOI1iEM'),
      link('github', 'AsciiTheme', 'https://github.com/markoblogo/AsciiTheme'),
    ],
    coverImage: cover('toki-pona-machine-mind', 'Toki Pona and the Machine Mind book cover'),
    series: 'Language & AI',
    category: 'Language & AI',
    formats: ['kindle', 'paperback', 'book-site'],
    featured: true,
    sortRank: 130,
    needsReview: false,
  },
  {
    id: 'christmas-carol-toki-pona',
    slug: 'christmas-carol-toki-pona',
    title: 'A Christmas Carol in Toki Pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Charles Dickens’ classic translated into Toki Pona with sitelen pona support.',
    tags: ['toki-pona', 'translation', 'european-classics'],
    links: [
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0G1N2YHD8'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0G1XVNPSL'),
      link('youtube', 'YouTube', 'https://youtu.be/ammjR4v58CM'),
    ],
    coverImage: cover('christmas-carol-toki-pona', 'A Christmas Carol in Toki Pona book cover'),
    series: tokiClassics,
    category: 'European Classics',
    formats: ['kindle', 'paperback'],
    featured: false,
    sortRank: 200,
    needsReview: false,
  },
  {
    id: 'cicero-toki-pona',
    slug: 'cicero-toki-pona',
    title: 'Cicero: On Duties in toki pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Cicero’s De Officiis translated into Toki Pona as part of the Stoic Wisdom series.',
    tags: ['toki-pona', 'stoicism', 'translation', 'cicero'],
    links: [
      link('series-site', 'Series', 'https://stoic.abvx.xyz/en'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0GL86LVF1'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0GLFN8KBX'),
      link('youtube', 'YouTube', 'https://youtu.be/61dVZDB-tYs'),
    ],
    coverImage: cover('cicero-toki-pona', 'Cicero On Duties in toki pona book cover'),
    series: stoicSeries,
    category: 'Stoic Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 210,
    needsReview: false,
  },
  {
    id: 'dao-de-jing-toki-pona',
    slug: 'dao-de-jing-toki-pona',
    title: 'Dao De Jing in Toki Pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Dao De Jing with Chinese text and Toki Pona in sitelen pona.',
    tags: ['toki-pona', 'dao', 'translation', 'chinese-wisdom'],
    links: [
      link('series-site', 'Series', 'https://dao-toki.abvx.xyz/'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0G4XNRS4W'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0G5MCFN2T'),
      link('youtube', 'YouTube', 'https://youtu.be/oWA-_FatU3E'),
    ],
    coverImage: cover('dao-de-jing-toki-pona', 'Dao De Jing in Toki Pona book cover'),
    series: chineseSeries,
    category: 'Chinese Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 220,
    needsReview: false,
  },
  {
    id: 'epictetus-enchiridion-toki-pona',
    slug: 'epictetus-enchiridion-toki-pona',
    title: 'Epictetus: The Enchiridion in toki pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'A Stoic handbook in Toki Pona with sitelen pona.',
    tags: ['toki-pona', 'stoicism', 'translation', 'epictetus'],
    links: [
      link('series-site', 'Series', 'https://stoic.abvx.xyz/en'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0GKWR5NL1'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0GKXXJGZV'),
      link('youtube', 'YouTube', 'https://youtu.be/DNgkm9tf6Cg'),
    ],
    coverImage: cover('epictetus-enchiridion-toki-pona', 'Epictetus Enchiridion in toki pona book cover'),
    series: stoicSeries,
    category: 'Stoic Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 230,
    needsReview: false,
  },
  {
    id: 'marcus-aurelius-meditations-toki-pona',
    slug: 'marcus-aurelius-meditations-toki-pona',
    title: 'Meditations of Marcus Aurelius in Toki Pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Marcus Aurelius’ Stoic classic reimagined in the world’s simplest language.',
    tags: ['toki-pona', 'stoicism', 'translation', 'marcus-aurelius'],
    links: [
      link('series-site', 'Series', 'https://stoic.abvx.xyz/en'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0FV3F1RC5'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0FVLPD69K'),
      link('youtube', 'YouTube', 'https://youtu.be/ILN2qILESH0'),
    ],
    coverImage: cover('marcus-aurelius-meditations-toki-pona', 'Meditations of Marcus Aurelius in Toki Pona book cover'),
    series: stoicSeries,
    category: 'Stoic Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 240,
    needsReview: false,
  },
  {
    id: 'seneca-shortness-of-life-toki-pona',
    slug: 'seneca-shortness-of-life-toki-pona',
    title: 'Seneca: On the Shortness of Life in toki pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Seneca’s On the Shortness of Life translated into Toki Pona.',
    tags: ['toki-pona', 'stoicism', 'translation', 'seneca'],
    links: [
      link('series-site', 'Series', 'https://stoic.abvx.xyz/en'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0GKCJ72PG'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0GL1ZBK18'),
      link('youtube', 'YouTube', 'https://youtu.be/_JL2xu4Sn70'),
    ],
    coverImage: cover('seneca-shortness-of-life-toki-pona', 'Seneca On the Shortness of Life in toki pona book cover'),
    series: stoicSeries,
    category: 'Stoic Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 250,
    needsReview: false,
  },
  {
    id: 'sunzi-art-of-war-toki-pona',
    slug: 'sunzi-art-of-war-toki-pona',
    title: 'Sunzi: The Art of War in toki pona',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Sunzi’s Art of War translated into Toki Pona as part of the Chinese Wisdom line.',
    tags: ['toki-pona', 'sunzi', 'translation', 'chinese-wisdom'],
    links: [
      link('series-site', 'Series', 'https://dao-toki.abvx.xyz/en'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.com/dp/B0GQTZFFVG'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.com/dp/B0GQXP442Z'),
      link('youtube', 'YouTube', 'https://youtu.be/sJdkHP6Pk-k'),
    ],
    coverImage: cover('sunzi-art-of-war-toki-pona', 'Sunzi Art of War in toki pona book cover'),
    series: chineseSeries,
    category: 'Chinese Wisdom',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 260,
    needsReview: false,
  },
  {
    id: 'chinese-wisdom-reader-guide',
    slug: 'chinese-wisdom-reader-guide',
    title: 'Free Kit / Reader’s Guide Chinese Wisdom in toki pona',
    type: 'free-edition',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Free reader’s guide for Chinese Wisdom in toki pona.',
    tags: ['toki-pona', 'free-book', 'reader-guide', 'chinese-wisdom'],
    links: [
      link('book-site', 'Site', 'https://toki-free.abvx.xyz/en'),
      link('pdf', 'PDF', '/media/books/chinese-wisdom-reader-guide.pdf'),
      link('youtube', 'YouTube', 'https://youtu.be/BOVyG1jP580'),
    ],
    coverImage: cover('chinese-wisdom-reader-guide', 'Chinese Wisdom reader guide cover'),
    series: chineseSeries,
    category: 'Free kits / companions',
    formats: ['pdf', 'book-site'],
    featured: false,
    sortRank: 300,
    needsReview: false,
  },
  {
    id: 'heart-sutra-toki-pona',
    slug: 'heart-sutra-toki-pona',
    title: 'Heart Sutra in toki pona / sitelen pona',
    type: 'free-edition',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Heart Sutra edition with traditional Chinese, Toki Pona, English, and sitelen pona.',
    tags: ['toki-pona', 'free-book', 'heart-sutra', 'chinese-wisdom'],
    links: [
      link('book-site', 'Site', 'https://toki-free.abvx.xyz/en'),
      link('pdf', 'PDF', '/media/books/heart-sutra-toki-pona.pdf'),
      link('youtube', 'YouTube', 'https://youtu.be/5q0eaRllDJQ'),
    ],
    coverImage: cover('heart-sutra-toki-pona', 'Heart Sutra in toki pona cover'),
    series: chineseSeries,
    category: 'Free kits / companions',
    formats: ['pdf', 'book-site'],
    featured: false,
    sortRank: 310,
    needsReview: false,
  },
  {
    id: 'toki-pona-readers-kit',
    slug: 'toki-pona-readers-kit',
    title: 'The Toki Pona Reader’s Kit',
    type: 'free-edition',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'Free reader kit for beginning to read Toki Pona editions.',
    tags: ['toki-pona', 'free-book', 'reader-kit', 'stoicism'],
    links: [
      link('book-site', 'Site', 'https://stoic.abvx.xyz/en'),
      link('pdf', 'PDF', '/media/books/toki-pona-readers-kit.pdf'),
      link('youtube', 'YouTube', 'https://youtu.be/F7fSBElppzI'),
    ],
    coverImage: cover('toki-pona-readers-kit', 'The Toki Pona Reader’s Kit cover'),
    series: stoicSeries,
    category: 'Free kits / companions',
    formats: ['pdf', 'book-site'],
    featured: false,
    sortRank: 320,
    needsReview: false,
  },
  {
    id: 'hryhorii-kosynka-dans-les-seigles',
    slug: 'hryhorii-kosynka-dans-les-seigles',
    title: 'Hryhorii Kosynka: Dans les seigles et autres nouvelles',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'French translation from the Ukrainian Modernism series.',
    tags: ['ukrainian-modernism', 'translation', 'french', 'kosynka'],
    links: [
      link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr'),
      link('pdf', 'PDF', '/media/books/hryhorii-kosynka-dans-les-seigles.pdf'),
      link('youtube', 'YouTube', 'https://youtu.be/4z3O2o2DNyc'),
    ],
    coverImage: cover('hryhorii-kosynka-dans-les-seigles', 'Hryhorii Kosynka French translation cover'),
    series: ukrSeries,
    category: 'Ukrainian-French',
    formats: ['pdf', 'series-site'],
    featured: false,
    sortRank: 400,
    needsReview: false,
  },
  {
    id: 'iouri-ianovski-le-maitre-du-navire',
    slug: 'iouri-ianovski-le-maitre-du-navire',
    title: 'Iouri Ianovski: Le Maitre du navire',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'French translation from the Ukrainian Modernism series.',
    tags: ['ukrainian-modernism', 'translation', 'french', 'ianovski'],
    links: [
      link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.fr/dp/B0GC9P9VKT'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.fr/dp/B0GCLLJZJ8'),
      link('youtube', 'YouTube', 'https://youtu.be/GqNzjSkvWvs'),
    ],
    coverImage: cover('iouri-ianovski-le-maitre-du-navire', 'Iouri Ianovski French translation cover'),
    series: ukrSeries,
    category: 'Ukrainian-French',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 410,
    needsReview: false,
  },
  {
    id: 'maik-johansen-le-voyage-du-savant-docteur-leonardo',
    slug: 'maik-johansen-le-voyage-du-savant-docteur-leonardo',
    title: 'Maik Johansen: Le Voyage du savant docteur Leonardo',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'French translation from the Ukrainian Modernism series.',
    tags: ['ukrainian-modernism', 'translation', 'french', 'johansen'],
    links: [
      link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.fr/dp/B0GDV7283Z'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.fr/dp/B0GDXGNT6B'),
      link('youtube', 'YouTube', 'https://youtu.be/LWRWb7CKE4I'),
    ],
    coverImage: cover('maik-johansen-le-voyage-du-savant-docteur-leonardo', 'Maik Johansen French translation cover'),
    series: ukrSeries,
    category: 'Ukrainian-French',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 420,
    needsReview: false,
  },
  {
    id: 'mykola-khvylovy-la-zone-du-sanatorium',
    slug: 'mykola-khvylovy-la-zone-du-sanatorium',
    title: 'Mykola Khvylovy: La zone du sanatorium',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'French translation from the Ukrainian Modernism series.',
    tags: ['ukrainian-modernism', 'translation', 'french', 'khvylovy'],
    links: [
      link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.fr/dp/B0G8V24GS2'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.fr/dp/B0G9G6JGDN'),
    ],
    coverImage: cover('mykola-khvylovy-la-zone-du-sanatorium', 'Mykola Khvylovy French translation cover'),
    series: ukrSeries,
    category: 'Ukrainian-French',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 430,
    needsReview: false,
  },
  {
    id: 'valerian-pidmohylny-la-ville',
    slug: 'valerian-pidmohylny-la-ville',
    title: 'Valerian Pidmohylny: La Ville',
    type: 'translation',
    primarySection: 'books',
    appearsIn: ['books'],
    status: 'released',
    summary:
      'French translation of the Ukrainian novel La Ville.',
    tags: ['ukrainian-modernism', 'translation', 'french', 'pidmohylny'],
    links: [
      link('series-site', 'Series', 'https://ukrmodernism.abvx.xyz/fr'),
      link('amazon-kindle', 'Kindle', 'https://www.amazon.fr/dp/B0GBY8CHYM'),
      link('amazon-paperback', 'Paperback', 'https://www.amazon.fr/dp/B0GC5ZMBTX'),
      link('youtube', 'YouTube', 'https://youtu.be/sHyGKkFdChY'),
    ],
    coverImage: cover('valerian-pidmohylny-la-ville', 'Valerian Pidmohylny French translation cover'),
    series: ukrSeries,
    category: 'Ukrainian-French',
    formats: ['kindle', 'paperback', 'series-site'],
    featured: false,
    sortRank: 440,
    needsReview: false,
  },
] satisfies Book[];
